const Draw = {
  clear(ctx,w,h,bg){ctx.clearRect(0,0,w,h);ctx.fillStyle=bg||'#fafbfc';ctx.fillRect(0,0,w,h)},
  colors:{primary:'#4f46e5',primaryLight:'#a5b4fc',accent:'#f59e0b',red:'#ef4444',green:'#10b981',blue:'#3b82f6',pink:'#ec4899',purple:'#8b5cf6',gray:'#94a3b8',dark:'#1e293b',light:'#f1f5f9',orange:'#f97316',teal:'#14b8a6'},
  line(ctx,x1,y1,x2,y2,o){o=o||{};ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=o.color||'#333';ctx.lineWidth=o.width||2;ctx.setLineDash(o.dash||[]);ctx.stroke();ctx.setLineDash([])},
  dashedLine(ctx,x1,y1,x2,y2,o){this.line(ctx,x1,y1,x2,y2,Object.assign({},o,{dash:[6,4]}))},
  rect(ctx,x,y,w,h,o){o=o||{};if(o.fill){ctx.fillStyle=o.fill;ctx.fillRect(x,y,w,h)}ctx.strokeStyle=o.color||'#333';ctx.lineWidth=o.width||2;ctx.setLineDash(o.dash||[]);ctx.strokeRect(x,y,w,h);ctx.setLineDash([])},
  circle(ctx,cx,cy,r,o){o=o||{};ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);if(o.fill){ctx.fillStyle=o.fill;ctx.fill()}ctx.strokeStyle=o.color||'#333';ctx.lineWidth=o.width||2;ctx.setLineDash(o.dash||[]);ctx.stroke();ctx.setLineDash([])},
  polygon(ctx,pts,o){o=o||{};if(!pts||pts.length<2)return;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.closePath();if(o.fill){ctx.fillStyle=o.fill;ctx.fill()}ctx.strokeStyle=o.color||'#333';ctx.lineWidth=o.width||2;ctx.setLineDash(o.dash||[]);ctx.stroke();ctx.setLineDash([])},
  fillPolygon(ctx,pts,color,alpha){ctx.save();ctx.globalAlpha=alpha||.3;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.closePath();ctx.fillStyle=color||this.colors.primaryLight;ctx.fill();ctx.restore()},
  label(ctx,text,x,y,o){o=o||{};ctx.save();ctx.font=(o.size||14)+'px "Segoe UI",sans-serif';ctx.textAlign=o.align||'center';ctx.textBaseline=o.baseline||'middle';ctx.fillStyle=o.color||'#333';if(o.bold)ctx.font='bold '+ctx.font;if(o.bg){const m=ctx.measureText(text);ctx.fillStyle=o.bg;ctx.fillRect(x-m.width/2-3,y-(o.size||14)/2-2,m.width+6,(o.size||14)+4);ctx.fillStyle=o.color||'#333'}ctx.fillText(text,x,y);ctx.restore()},
  point(ctx,x,y,label,o){o=o||{};ctx.beginPath();ctx.arc(x,y,o.r||4,0,Math.PI*2);ctx.fillStyle=o.color||this.colors.primary;ctx.fill();if(label)this.label(ctx,label,x+(o.labelOffsetX||8),y+(o.labelOffsetY||-8),{size:13,color:o.color||this.colors.dark,bold:true})},
  rightAngle(ctx,x,y,dx,dy,size){size=size||10;ctx.strokeStyle='#666';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x+dx,y);ctx.lineTo(x+dx,y+dy);ctx.lineTo(x,y+dy);ctx.stroke()},
  angleArc(ctx,x,y,r,sAngle,eAngle,o){o=o||{};ctx.beginPath();ctx.arc(x,y,r,sAngle,eAngle);ctx.strokeStyle=o.color||'#666';ctx.lineWidth=o.width||1.5;ctx.stroke();if(o.label){const m=(sAngle+eAngle)/2;const lx=x+(r+15)*Math.cos(m);const ly=y+(r+15)*Math.sin(m);this.label(ctx,o.label,lx,ly,{size:13,color:o.color||'#666'})}},
  arrow(ctx,x1,y1,x2,y2,o){o=o||{};const dx=x2-x1,dy=y2-y1,len=Math.sqrt(dx*dx+dy*dy);if(len<1)return;const nx=dx/len,ny=dy/len;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=o.color||this.colors.accent;ctx.lineWidth=o.width||2.5;ctx.stroke();const hl=10;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-hl*nx+hl/2*ny,y2-hl*ny-hl/2*nx);ctx.lineTo(x2-hl*nx-hl/2*ny,y2-hl*ny+hl/2*nx);ctx.closePath();ctx.fillStyle=o.color||this.colors.accent;ctx.fill()},
  tag(ctx,text,x,y,bg,color){ctx.save();ctx.font='bold 13px "Segoe UI",sans-serif';const m=ctx.measureText(text),pw=8,ph=4;ctx.fillStyle=bg||this.colors.primaryLight;ctx.beginPath();ctx.roundRect(x-m.width/2-pw,y-10-ph,m.width+pw*2,20+ph*2,4);ctx.fill();ctx.fillStyle=color||'#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y);ctx.restore()},
  box3D(ctx,x,y,w,h,d,o){o=o||{};const c=o.color||this.colors.primary;const lc=o.lineColor||'#333';const lw=o.lineWidth||2;ctx.fillStyle=o.frontColor||c+'40';ctx.fillRect(x,y,w,h);ctx.strokeStyle=lc;ctx.lineWidth=lw;ctx.strokeRect(x,y,w,h);const top=[{x,y},{x:x+d,y:y-d},{x:x+w+d,y:y-d},{x:x+w,y}];ctx.fillStyle=o.topColor||c+'60';this.fillPolygon(ctx,top,ctx.fillStyle,1);this.polygon(ctx,top,{color:lc,width:lw});const right=[{x:x+w,y},{x:x+w+d,y:y-d},{x:x+w+d,y:y-d+h},{x:x+w,y:y+h}];ctx.fillStyle=o.rightColor||c+'20';this.fillPolygon(ctx,right,ctx.fillStyle,1);this.polygon(ctx,right,{color:lc,width:lw})},
  grid(ctx,x,y,cols,rows,cellSize,o){o=o||{};const color=o.color||'#ddd';const lw=o.lineWidth||1;for(let r=0;r<=rows;r++)this.line(ctx,x,y+r*cellSize,x+cols*cellSize,y+r*cellSize,{color,width:lw});for(let c=0;c<=cols;c++)this.line(ctx,x+c*cellSize,y,x+c*cellSize,y+rows*cellSize,{color,width:lw})}
};
